@startuml

entity "Clientes" as Clientes{
    * codigo: INT <<PK>>
    --
    * nombres: VARCHAR(50)
    * apellidos: VARCHAR (50)
    telefono: VARCHAR(15)
    * fechaRegistro: DATE
    * cantidadEntradas: INT
}

entity "Salas" as Salas{
    * codigo: INT <<PK>>
    --
    * nombre: VARCHAR(10)
    * capacidad: INT
}

entity "Peliculas" as Peliculas{
    * codigo: INT <<PK>>
    * nombre: VARCHAR (70)
    * director: VARCHAR (50)
    * duracion_minutos: INT
    * clasificacion: VARCHAR(5)
}

entity "Funciones" as Funciones{
    * codigo: INT <<PK>>
    --
    * codigo_pelicula: INT <<FK>>
    * codigo_sala: INT <<FK>>
    * fecha: DATE
    * hora_inicio: TIME
    * hora_fin: TIME
    * precio_entrada: DECIMAL(10,2)
}

entity "Asientos" as Asientos{
    * codigo_asiento: INT <<PK>>
    --
    * codigo_sala: INT <<FK>>
    * tipo: VARCHAR(20)
}

entity "Boletos" as Boletos{
    * codigo: INT <<PK>>
    --
    * codigo_factura: INT <<FK>>
    * codigo_funcion: INT <<FK>>
    * codigo_asiento: INT <<FK>>
    * precio: DECIMAL(10,2)

}
entity "Ventas" as Ventas{
    * codigo: INT <<PK>>
    --
    * precio_total: DECIMAL(10,2)
    * fecha: DATE
    * hora: TIME
    * codigo_cliente: INT <<FK>>

}

entity "Generos" as Generos{
    * codigo: INT <<PK>>
    --
    nombre: VARCHAR(30)
}

entity "Generos Peliculas" as Generos_Peliculas{
    * codigo_pelicula: int <<FK>>
    * codigo_genero: int <<FK>>
}

Generos_Peliculas ||--o{ Generos : "tiene"
"Generos_Peliculas" ||--o{ Peliculas : "tiene"

' Una Sala tiene muchos Asientos
Salas ||--o{ Asientos : "tiene"

' Una Película tiene muchas Funciones
Peliculas ||--o{ Funciones : "se proyecta en"

' Una Sala tiene muchas Funciones
Salas ||--o{ Funciones : "alberga"

' Un Cliente tiene muchas Ventas
Clientes ||--o{ Ventas : "paga"

' Una Venta tiene muchos Boletos (Detalles)
Ventas ||--|{ Boletos : "desglosa"

' Una Función tiene muchos Boletos vendidos
Funciones ||--o{ Boletos : "emite"

' Un Asiento puede estar en muchos Boletos (en diferentes funciones)
Asientos ||--o{ Boletos : "se asigna a"
@enduml